### ISSUE TITLE
Add support for Boot build-file

### ISSUE THREAD

**Issue by nicorikken** [atom/language-clojure#25]
[Boot](http://boot-clj.com/) uses build files using the _build.boot_ filename. The current language specification doesn't recognize these files as Clojure files. The code is however strict Clojure.

I'd like to add support for the _boot.build_ files. I'm however not sure if this would best be done by adding _boot_ as a fileType, or by adding a more specific kind of fileType for the full filename _build.boot_.

I hope someone else can test drive this one-line change, so I don't have to set up a development environment.

**Comment by 50Wliu** [comment]
@nicorikken Either will work.

**Comment by nicorikken** [comment]
I created a pull request based on the above suggestion, making it as specific as possible, as I didn't encounter other .boot files and want to avoid future conflicts. It was a blind change, so please testdrive it, even though the build passed.

**Comment by martinklepsch** [comment]
This can be closed :)

**Comment by 50Wliu** [comment]
Thanks @martinklepsch :).
