### ISSUE TITLE
Opening curly bracket and first keyword are syntax colored as method name when a literal map is used in function call position

### ISSUE THREAD

**Issue by WalterGR** [atom/language-clojure#35]
Atom 1.3.2 on OS X 10.10.5.

Repro:

Type the following in a `.clj` file.

![language-clojure--opening-curly-bracket-and-key-colored-as-function-name](https://cloud.githubusercontent.com/assets/380880/12222667/8dc49930-b777-11e5-94ba-9f3bd912a967.png)

Expected:

The opening curly bracket is syntax colored the same as the closing curly bracket, and the first key is syntax colored the same as the rest of the keys.

Actual:

It appears as in the screenshot above.

**Comment by WalterGR** [comment]
(Added Atom and OS X versions to description.)

**Comment by wingyplus** [comment]
I see this issue was solved (with [test case](https://github.com/atom/language-clojure/blob/master/spec/grammar-spec.coffee#L201)). Can issue close?

**Comment by 50Wliu** [comment]
Yup, thanks @wingyplus!
