### ISSUE TITLE
Test Cases?

### ISSUE THREAD

**Issue by oakmac** [atom/language-clojure#38]
Are there are any tests for this package?

Looking at some of the open Issues #23, #32, #33, #35 - it would be nice to develop some expected test cases for these and ensure functionality moving forward.

I suppose a more general question is: are there test cases for any grammar package in Atom?

**Comment by 50Wliu** [comment]
> are there test cases for any grammar package in Atom?

Yes, most languages have somewhat decent spec coverage by now.  Some leaders in the field are [language-javascript](https://github.com/atom/language-javascript/blob/master/spec/javascript-spec.coffee), [language-go](https://github.com/atom/language-go/blob/master/spec/go-spec.coffee), and [language-c](https://github.com/atom/language-c/blob/master/spec/c-spec.coffee).

This package also has tests, but unfortunately the only test right now is to make sure the grammar loads...https://github.com/atom/language-clojure/blob/master/spec/grammar-spec.coffee.

(Also, the autoindent issues are much, much harder to solve than normal syntax highlighting ones, as they require knowledge of both the language and the arcane and barely working autoindent regexes).

If you'd like to take a stab at writing some specs, please feel free to!  I'd love to help you along if necessary.

**Comment by oakmac** [comment]
Thanks for the response! I'm tempted to dig into this a bit further.

> Also, the autoindent issues are much, much harder to solve than normal syntax highlighting ones, as they require knowledge of both the language and the arcane and barely working autoindent regexes

Where are those autoindent regexes located?

**Comment by 50Wliu** [comment]
language-clojure doesn't even have any auto-indent regexes, heh.  You can find an example of them here though: https://github.com/atom/language-go/blob/master/settings/language-go.cson
With a general auto-indent rewrite in progress at atom/atom#10384.

**Comment by oakmac** [comment]
Very helpful; thank you :)
