### ISSUE TITLE
Line breaks marked as invalid trailing whitespace

### ISSUE THREAD

**Issue by iconara** [atom/language-clojure#51]
I'm not sure when this started happening, or if it's Atom's fault or this package's fault, but last time I edited Clojure in Atom (in mid August I think) it looked fine, but now (in mid September) every single line break is marked as invalid trailing whitespace.

I'm using language-clojure package in combination with [trailing-spaces](https://atom.io/packages/trailing-spaces) to show trailing whitespace, but as far as I can tell all that package does is highlight what other parts of Atom are marking as trailing whitespace, it only seems to contain styling and no logic to detect trailing whitespace.

![trailing-whitespace](https://cloud.githubusercontent.com/assets/73330/18463096/09c1fb18-7988-11e6-967f-2c686ac02e51.png)

This is how the line breaks end up in the DOM:

![screen shot 2016-09-13 at 08 01 14](https://cloud.githubusercontent.com/assets/73330/18463132/53b4d1aa-7988-11e6-93e3-39ef445aa9d0.png)

This doesn't happen in any other language I'm regularly edit with Atom, that's why I'm reporting it here. Could it be something in the Clojure grammar that's marking line breaks as invalid whitespace?

It's UNIX line feeds, so it's not that it's Windows line endings or anything like that.

**Comment by iconara** [comment]
Oh, and if there is actual trailing whitespace it's correctly identified and the line break is not, as expected:

![screen shot 2016-09-13 at 10 07 45](https://cloud.githubusercontent.com/assets/73330/18465997/f9fb4452-7999-11e6-8143-017a168e3caf.png)

**Comment by 50Wliu** [comment]
Hey there @iconara.  I'm not familiar with Clojure, so please bear with me.  Is trailing whitespace actually invalid (ie, the code will not compile/run), or is it simply considered "best practices" to not have trailing whitespace?

**Comment by iconara** [comment]
It's the same as most other languages, it's purely an aesthetic issue.

**Comment by 50Wliu** [comment]
Ok, thanks.
