### ISSUE TITLE
Match keywords named with latex

### ISSUE THREAD

**Issue by pjago** [atom/language-clojure#57]
Hi, I am new to atom and I wish to allow keywords to color Unicode symbols as in 
https://github.com/JunoLab/atom-latex-completions
![image](https://cloud.githubusercontent.com/assets/7795187/20582904/04c49502-b1c4-11e6-9f13-67aae8b87f83.png)
How can I contribute?

**Comment by 50Wliu** [comment]
The grammar file is here: https://github.com/atom/language-clojure/blob/master/grammars/clojure.cson
The hard part is finding which section you need to change.  Use ctrl-alt-shift-P (or cmd-shift-P on Mac) to look at the scopes of the `::x` and `::y` lines, then search for them in the grammar file.

**Comment by PEZ** [comment]
This is now fixed in [Calva Formatter](https://github.com/BetterThanTomorrow/calva-fmt), for any VS Code Clojurians reading this.
