### ISSUE TITLE
Syntax highlighting when string is first element of list

### ISSUE THREAD

**Issue by smithtim** [atom/language-clojure#79]
*Edit by @rsese to add issue template*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![screen shot 2018-10-24 at 10 58 49 am](https://user-images.githubusercontent.com/25237756/47451146-dcca6100-d77b-11e8-8f46-6465ec991a61.png)

The first element of the list is being highlighted as a function, when it should be highlighted as a string like the others.

For numbers, the highlighting is correct:

![screen shot 2018-10-24 at 11 06 02 am](https://user-images.githubusercontent.com/25237756/47451508-d4bef100-d77c-11e8-84db-cd80f0ae96a7.png)

### Steps to Reproduce

1. Create a `test.clj` file with the content:

```clj
("foo" "bar" "baz")
```

**Expected behavior:** [What you expect to happen]

All 3 strings to be colored the same.

**Actual behavior:** [What actually happens]

![screen shot 2018-10-24 at 10 58 49 am](https://user-images.githubusercontent.com/25237756/47451146-dcca6100-d77b-11e8-8f46-6465ec991a61.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
atom-nightly -v
Atom    : 1.34.0-nightly5
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

macOS 10.12.6

---

![screen shot 2018-10-24 at 10 58 49 am](https://user-images.githubusercontent.com/25237756/47451146-dcca6100-d77b-11e8-8f46-6465ec991a61.png)

The first element of the list is being highlighted as a function, when it should be highlighted as a string like the others.

For numbers, the highlighting is correct:

![screen shot 2018-10-24 at 11 06 02 am](https://user-images.githubusercontent.com/25237756/47451508-d4bef100-d77c-11e8-84db-cd80f0ae96a7.png)

atom version: 1.32.0
language-clojure version: 0.22.7

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce this highlighting with `("foo" "bar" "baz")` on macOS 10.12.6 with 1.34.0-nightly5.  Do you think https://github.com/atom/language-clojure/issues/63 is the same, or different but similar issue?

Also, for future issues please use the issue template, the information in the template is super helpful for us when triaging issues.

**Comment by smithtim** [comment]
#63 may be the same issue.  Perhaps the two could be merged by combining the examples from each?  Here is another example illustrating the behavior:

![image](https://user-images.githubusercontent.com/25237756/47877792-f7cf4d80-ddd9-11e8-9978-8d5d3c52b204.png)

Notice that `"foo"` and `"how"` are blue, `"bar"` and `"baz"` are green, and `"are you"` and `"test"` are gray.  Also, `1` and `2` are orange and `3` is green.

**Comment by rsese** [comment]
> #63 may be the same issue. Perhaps the two could be merged by combining the examples from each? Here is a fuller example illustrating the behavior:

Thanks I'll go ahead and do that :+1:, we can always reopen this if necessary.
