### ISSUE TITLE
False-positive, but inconsistent, parsing of :/ keyword

### ISSUE THREAD

**Issue by peter-kehl** [atom/language-clojure#84]
Hi. Thank you for language-clojure,

`#{:| :/ :- :L :+}` generates a "Read error: Invalid use of / in symbol name". That is incorrect - the map literal works (in current CLJ 1.10). Also note: the literal is for a map of keywords, but the error mentions 'symbol'.

That bug is local/inconsistent. If you have a keyword `:/` on its own, it parses well.

**Comment by rsese** [comment]
Thanks for the report!

Can you share a minimal full code example that we can copy and paste that shows the problem?  It's helpful in general but also specifically for me since I haven't used Clojure before.

**Comment by rsese** [comment]
Oh also, please use the issue template when creating issues - the template details and format is super helpful for us when triaging issues.

**Comment by peter-kehl** [comment]
Hi Robert @rsese.

The minimal full code example: `:/`.
That is a literal for a keyword whose name is one character long, containing a slash. However, it upsets Atom:
![image](https://user-images.githubusercontent.com/4270240/51339881-6cfa0880-1a42-11e9-972a-f69b341216d6.png)

That syntax works in `clj` 1.10.0 (Clojure REPL):
![image](https://user-images.githubusercontent.com/4270240/51339924-88fdaa00-1a42-11e9-8f5d-09819894de7a.png)

**Comment by rsese** [comment]
lol gotcha, thanks :+1:

Also I think I misunderstood your report, so just to circle back to your original comments, you mentioned:

> #{:| :/ :- :L :+} generates a "Read error: Invalid use of / in symbol name". 

This wouldn't be generated by language-clojure, this package just provides syntax highlighting.

Are you using a specific package for Clojure linting/validation?  If so, that would be the package to report the error to.
